language: node_js
node_js:
- stable
- '6'
- '4'
before_script:
- npm install
script:
- npm run dist
- tar -cvf makerbuild-electron.tar .
- gzip makerbuild-electron.tar
deploy:
  provider: releases
  user: munchkinhalfling
  file:
  - dist/makerbuild-electron-1.0.0.AppImage
  - makerbuild-electron.tar.gz
  password:
    secure: k2AEdf1cPlCcxWdOjY2+cFe/guCwANawcd3reun2wTYPZPbTISiXutW9F47aCn/xSRnph/x6pCVHQAlnA/2PG0X9i/pZkJ0TXr2AjGna/pLdctiGjU7UJTPoNZ1nyEmde1DwBVg44ZX9w8qpUr4+4B0dztOahgUJHYAlVNHDG6iPvrWpLJgC8/kf3I9O7so2o5bjghOXFPKOpk4h7DuNbK1NcgfHYpsx8qSu14kk/r6nawr6wE4MjnaSSGcYEBgij6ObnEhVm+aSluCAI93fvPJdbxBcf3XwK4hehUSpCqVrZDcZM1oqnhuxl4CsGSvzYnz6mdf/rtFKl3hOPN1OPq8xhjBN9xeDSWlq6fREJD45U9HxmH8W1DGPgUhB3Xl1NatYchYl0bshJeOMQLn2KG5YEB+wkGRGzdHrBtZ+V6Crmge8Ui/SbDusiYB1G2gUcjwfKBjXG59IbU8og94PYZfWYafmIKQFPAAKYthYtx/nowGrUGbi+oDLYGdEomhwi3Gg9U8qW1EAwaocyUqyFAqHuj0vqrULpCahcZIFUloDcfDwDkdfHtjtllSQc9eqHybAgxP9kID5kR/WYGRIIKnkk8hteyT5MeAsraL3quSOQGlSJXnYrWo10VM10GvCe66OO5fokLuoOowEMyuBH8fAqgIAHJQKg0VE1MSX2Dk=
  on:
    tags: true